### PR TITLE
Generate https URLs by default

### PR DESCRIPTION
**Pull request by abitrolly**
This just makes configs a little bit less verbose.

### CODE REVIEW

**Review by Angatar — COMMENTED** [review]
Thanks for your interest in this container and thank you for this pull request!
I agree with you that in most use cases the URL_PATTERN env is probably set to https, so that making it the default value could have saved us a setting line and would be more consistent with most deployments.
However, it seems that this container is quite regularly pulled and we don't know how many deployments are currently using http instead of https. Merging this pull request would potentially break these "http" deployments on their next container pull if the URL_PATTERN has not been explicitly set to http.
So I'm sorry to close this well formed pull request without merging it to avoid to break these potential deployments; it would have completely made sense to merge it with fewer users.

**Comment by abitrolly** [comment]
Well, perhaps it needs a different tag.

**Comment by Angatar** [comment]
Well it would be a new tag to maintain but I would if there was a consequent functional gain. However it is a good practice to set all environment variables in production to avoid to be impacted by any substantial change in default values, so the gain here would mostly be limited to rapid test deployments made with docker commands (not docker-compose nor k8s) and these test deployments are often made with no needs of https : therefore these users will have to add the setting line you intend to remove to go with http :wink:
To simplify the handling of multiple setting lines of your docker deployment for this container, you could make use of a docker-compose file.
Thanks again for your input! I'm closing this pull request.

**Comment by abitrolly** [comment]
Maintaining a lot of options is a burden, indeed. I still can not get admin interface rendered, but it is better open a separate issue.

**Pull request closed without merging**
